version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ai-healthcare-system:latest
    container_name: ai-healthcare-app
    command: echo "Placeholder container — will configure later"
